image: node:20

pipelines:
  branches:
    Main:
      - step:
          name: "Build and Deploy to Server"
          caches:
            - node
          script:
            - echo "Installing dependencies"
            - npm install --legacy-peer-deps
            - echo "Running npm run build"
            - npm run build
            - echo "Listing the contents of the current directory"
            - ls -l
            - echo "Listing the dist directory contents"
            - ls -l dist/  # Check that dist/ exists
            - echo "Installing required packages (sshpass and rsync)"
            - apt-get update && apt-get install -y apt-utils sshpass rsync
            - echo "Ensuring remote directory exists"
            - sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no "$SERVER_USER"@"$SERVER_IP" "mkdir -p $REMOTE_PATH"
            - echo "Testing SSH connection"
            - sshpass -p "$SERVER_PASSWORD" ssh -vvv -o StrictHostKeyChecking=no "$SERVER_USER"@"$SERVER_IP" "echo 'SSH is working'"
            - echo "Deploying via SSH with debugging"
            - sshpass -p "$SERVER_PASSWORD" rsync -avz -vv --delete dist/ "$SERVER_USER"@"$SERVER_IP":"$REMOTE_PATH"
          deployment: production
